# Generated by Django 3.0.6 on 2020-05-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200525_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='status',
            field=models.CharField(choices=[('C', 'создано'), ('A', 'одобрено'), ('D', 'отклонено')], default='C', max_length=1),
        ),
    ]
