# Generated by Django 3.0.6 on 2020-05-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0004_auto_20200527_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
