# Generated by Django 3.0.6 on 2020-05-29 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0005_auto_20200529_0801'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
    ]
